services:
  ddfinance-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
      - "7068:7068"
    environment:
      - PostgresConnection=Host=postgres;Database=dd_finance;Username=postgres;Password=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddfinance
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
